services:
  twitch-telegram-notifier:
    build: .
    container_name: twitch-telegram-notifier
    user: 1000:1000
    volumes:
      - ./config.ini:/opt/twitch/config.ini:ro
    restart: unless-stopped
